sudo: false
language: node_js
cache:
  bundler: true
  directories:
  - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
before_deploy:
- npm install browserify coffeeify
- mkdir -p deploy/meshblu-ms-azure-ml/latest
- mkdir -p deploy/meshblu-ms-azure-ml/$TRAVIS_TAG
- node_modules/.bin/browserify -s Connector -t coffeeify connector.js > deploy/meshblu-ms-azure-ml/latest/meshblu-ms-azure-ml.js
- gzip deploy/meshblu-ms-azure-ml/latest/meshblu-ms-azure-ml.js
- mv deploy/meshblu-ms-azure-ml/latest/meshblu-ms-azure-ml.js.gz deploy/meshblu-ms-azure-ml/latest/meshblu-ms-azure-ml.js
- cp deploy/meshblu-ms-azure-ml/latest/meshblu-ms-azure-ml.js deploy/meshblu-ms-azure-ml/$TRAVIS_TAG/meshblu-ms-azure-ml.js
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: ItQFt+eqduvqEOWI4EbT7TLLsBbbcrmIFOEb1xwNc65NNnEfJpJWDrLUJMlmcrdkJdGDuPHNV+JuEOMlMLMZuN2gRGRgf94ZTvBK4j2zXbDEJapZ+uG76mYN/F7oPIyIiljDphJ+q6PVCzYubhejwr7vHo5vLt3wzmaZf9swM80=
    on:
      tags: true
      all_branches: true
  - provider: s3
    access_key_id: AKIAJH2D5IPIRHYJT5IA
    secret_access_key:
      secure: "d71tqSTJmVoGUby4tVwjjCmb/O/feCfNBN0tabSRPdnM3bWjNgGaPH2dUCGlOvOZLbhlTf/IGJVI1Uny2TURDfZUD8HJccUaSaJlC3sT6XTf8BpUPQucZEOZ9gzhbN6CPnvPkEV+cjvDAajwogjSpq5ShZlEEm3dayPj0Qxif6IPvGP6Kle1CbmT6ZNxcQK5ABVHQEsltO/BXxosa9x31tPKTkYE/gfweFobsw3I4QEsbe4nY12c0mkQrz8JukhDRCL0WugoK8DzbK6ajr/QG1FR+WHYWGlUzqInUYOUyh+3ZLKcFBcdE1PcdgjN7kgAs2dBUO9uV930lVbJf+7whMXiE2QucFLU6ETSiqD5k+8xEz+RrjbE92mdSeSE/NnqkRSkgUBwfzG7SmodB/UXkbT7h8z3HSg3VsMHj3+IGhhO7FUvtmCdpsdng0EIrq/kttgkOaN2pyIr1Ii4b2EgPAggwqMjqklWrHUQp+ffWNJGSzO6etZI5om8uji5+eH33tnTm+ppRZrjLU9XaAGQV3d/NgBIauOdc4gWaiSeP5iW1MwclPWeX6KEMh/qvClj5tTzsLV7B9wwOOUj/7HSllKmQ0dUiRjI8Tg/9kX9kOKt+w3V5yqi7FBtEjzQZ4swUpW+mOv2Qgk/iUnutkKiF2zp2cDbVSxtNz0auT7AiI0="
    bucket: octoblu-cdn
    region: us-west-2
    skip_cleanup: true
    detect_encoding: true
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
